/*
 * Copyright (c) 2026 LeastAction Labs, Inc.
 * This file is part of LeastAction and is licensed under the
 * LeastAction Sustainable Use License (see LICENSE.md) or, for files
 * marked EE, the LeastAction Enterprise Edition License (see LICENSE_EE.md).
 * Use of this file outside those terms is not permitted.
 */
import { useEffect, useRef, useState } from 'react';

import { Box, CircularProgress, Tooltip, Typography } from '@mui/material';
import { CronExpressionParser } from 'cron-parser';

import { COLORS, FONT_SIZES } from '@/constants';
import { STATUS_COLORS } from '@/constants/logConstants';
import { useRecentRuns } from '@/hooks/useRecentRuns';
import type { TaskHistoryEntry } from '@/hooks/useTaskHistory';
import { formatDateTimeFull } from '@/utils/timeFormat';

const SLOT_COUNT = 15;

export interface RecentRunsStripProps {
  taskLaui: string;
  /** Called when a run box is clicked, with that run's session id. */
  onRunClick: (sessionId: string) => void;
  /** Changing this forces the strip to re-fetch (e.g. on table refresh). */
  refreshKey?: number;
  /** Cron expression for the task; "ADHOC" or absent means ad-hoc. */
  frequency?: string;
  /** ISO timestamp of the next scheduled run. */
  nextRunDate?: string;
}

/**
 * logical_date in log files is stored as UTC with no Z suffix, e.g.
 * "2026-06-21T07:57:00". Appending Z makes the browser parse it as UTC
 * instead of local time.
 */
function parseLogicalDateUtc(s: string): number {
  if (!s) return NaN;
  const normalized = s.endsWith('Z') || /[+-]\d{2}:\d{2}$/.test(s) ? s : s + 'Z';
  return new Date(normalized).getTime();
}

interface Slot {
  /** UTC ms of this logical date. */
  tsMs: number;
  /** Run entry from the task's own log, or null for a pending slot. */
  run: TaskHistoryEntry | null;
}

/**
 * A horizontal strip of a task's recent runs.
 *
 * Each slot comes directly from this task's own log files — the logical_date
 * stored in the log is used as-is (the backend truncates it to the exact cron
 * tick). Pending dashed boxes are generated by walking the cron expression
 * forward from the last run's logical_date up to now.
 *
 * Ad-hoc tasks just show their own runs with no pending slots.
 */
export default function RecentRunsStrip({
  taskLaui,
  onRunClick,
  refreshKey = 0,
  frequency,
  nextRunDate,
}: RecentRunsStripProps) {
  const isAdhoc = !frequency || frequency === 'ADHOC';
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [inView, setInView] = useState(false);

  useEffect(() => {
    const el = containerRef.current;
    if (!el || inView) return;
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          setInView(true);
          observer.disconnect();
        }
      },
      { rootMargin: '100px' },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [inView]);

  const { runs, latestRuns, loading } = useRecentRuns(taskLaui, SLOT_COUNT, inView, refreshKey);

  // Merge regular session logs + latest_*.log entries, keyed by logical_date
  // (UTC ms). Regular logs represent completed runs and take precedence.
  const runsByTs = new Map<number, TaskHistoryEntry>();
  for (const r of latestRuns) {
    const ts = parseLogicalDateUtc(r.logical_date);
    if (!isNaN(ts)) runsByTs.set(ts, r);
  }
  for (const r of runs) {
    const ts = parseLogicalDateUtc(r.logical_date);
    if (!isNaN(ts)) runsByTs.set(ts, r);
  }

  // All known runs sorted oldest → newest.
  const allRuns = Array.from(runsByTs.entries())
    .sort(([a], [b]) => a - b)
    .map(([, r]) => r);

  // Scroll to the right end once loading finishes so the latest run is visible.
  const prevLoadingRef = useRef(true);
  useEffect(() => {
    if (prevLoadingRef.current && !loading) {
      const el = containerRef.current;
      if (el) el.scrollLeft = el.scrollWidth;
    }
    prevLoadingRef.current = loading;
  }, [loading]);

  // Pending slots: cron ticks that fired after the last run's logical_date
  // and are <= now with no corresponding log entry.
  const pendingSlots: number[] = (() => {
    if (isAdhoc) return [];

    const nowMs = Date.now();
    const lastTs =
      allRuns.length > 0 ? parseLogicalDateUtc(allRuns[allRuns.length - 1].logical_date) : NaN;

    // No runs yet — show a single pending slot if the task is overdue.
    if (isNaN(lastTs)) {
      if (nextRunDate) {
        const nextMs = parseLogicalDateUtc(nextRunDate);
        if (!isNaN(nextMs) && nextMs <= nowMs) return [nextMs];
      }
      return [];
    }

    try {
      const startDate = new Date(lastTs + 1);
      const endDate = new Date(nowMs);
      if (startDate >= endDate) return [];

      const expr = CronExpressionParser.parse(frequency, {
        currentDate: startDate,
        startDate,
        endDate,
        utc: true,
      });

      const slots: number[] = [];
      while (true) {
        try {
          const tickMs = expr.next().toDate().getTime();
          if (tickMs > nowMs) break;
          if (!runsByTs.has(tickMs)) slots.push(tickMs);
        } catch {
          break;
        }
      }
      return slots;
    } catch {
      return [];
    }
  })();

  const slots: Slot[] = [
    ...allRuns.map((r) => ({ tsMs: parseLogicalDateUtc(r.logical_date), run: r })),
    ...pendingSlots.map((tsMs) => ({ tsMs, run: null })),
  ]
    .filter((s) => !isNaN(s.tsMs))
    .sort((a, b) => a.tsMs - b.tsMs)
    .slice(-SLOT_COUNT);

  const showEmpty = !loading && (isAdhoc ? allRuns.length === 0 : slots.length === 0);

  return (
    <Box
      ref={containerRef}
      sx={{
        display: 'flex',
        alignItems: 'center',
        gap: 0.5,
        overflowX: 'auto',
        maxWidth: '100%',
        minHeight: 18,
        '&::-webkit-scrollbar': { height: 4 },
        '&::-webkit-scrollbar-thumb': {
          backgroundColor: COLORS.SCROLLBAR_THUMB,
          borderRadius: 2,
        },
      }}
    >
      {loading && allRuns.length === 0 ? (
        <CircularProgress size={12} sx={{ color: 'var(--text-secondary)' }} />
      ) : showEmpty ? (
        <Typography sx={{ fontSize: FONT_SIZES.XXS, color: 'var(--text-secondary)' }}>—</Typography>
      ) : isAdhoc ? (
        allRuns
          .slice(-SLOT_COUNT)
          .map((run, idx) => (
            <RunBox
              key={`${run.session_id ?? run.fileName}-${idx}`}
              run={run}
              onRunClick={onRunClick}
            />
          ))
      ) : (
        slots.map((slot, idx) =>
          slot.run ? (
            <RunBox key={`run-${idx}`} run={slot.run} onRunClick={onRunClick} />
          ) : (
            <PendingBox key={`pending-${idx}`} slotMs={slot.tsMs} />
          ),
        )
      )}
    </Box>
  );
}

function RunBox({
  run,
  onRunClick,
}: {
  run: TaskHistoryEntry;
  onRunClick: (sessionId: string) => void;
}) {
  const color = (STATUS_COLORS[run.status] ?? STATUS_COLORS.pending).dot;
  return (
    <Tooltip
      arrow
      placement="top"
      PopperProps={{
        modifiers: [
          { name: 'flip', enabled: true },
          { name: 'preventOverflow', enabled: true, options: { boundary: 'window' } },
        ],
      }}
      title={formatDateTimeFull(run.logical_date)}
    >
      <Box
        onClick={(e) => {
          e.stopPropagation();
          if (run.session_id) onRunClick(run.session_id);
        }}
        sx={{
          width: 12,
          height: 16,
          flexShrink: 0,
          borderRadius: 0.5,
          bgcolor: color,
          cursor: run.session_id ? 'pointer' : 'default',
          opacity: 0.75,
          transition: 'opacity 0.15s ease',
          '&:hover': { opacity: 1 },
        }}
      />
    </Tooltip>
  );
}

function PendingBox({ slotMs }: { slotMs: number }) {
  const label = new Date(slotMs).toISOString().replace('.000Z', '').replace('Z', '');
  return (
    <Tooltip
      arrow
      placement="top"
      PopperProps={{
        modifiers: [
          { name: 'flip', enabled: true },
          { name: 'preventOverflow', enabled: true, options: { boundary: 'window' } },
        ],
      }}
      title={formatDateTimeFull(label)}
    >
      <Box
        sx={{
          width: 12,
          height: 16,
          flexShrink: 0,
          borderRadius: 0.5,
          border: '1.5px dashed',
          borderColor: 'var(--text-secondary)',
          opacity: 0.6,
        }}
      />
    </Tooltip>
  );
}
