/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QueryImport } from './routes/query'
import { Route as PathImport } from './routes/path'
import { Route as McpTokenImport } from './routes/mcp-token'
import { Route as MarketplaceImport } from './routes/marketplace'
import { Route as ExploreImport } from './routes/explore'
import { Route as DebugImport } from './routes/debug'
import { Route as ChangePasswordImport } from './routes/change-password'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as PublicRegisterImport } from './routes/public/register'
import { Route as PublicMarketplaceCallbackImport } from './routes/public/marketplace-callback'
import { Route as PublicLoginImport } from './routes/public/login'
import { Route as PublicCallbackImport } from './routes/public/callback'
import { Route as AiCreateImport } from './routes/ai.create'

// Create/Update Routes

const QueryRoute = QueryImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any)

const PathRoute = PathImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRoute,
} as any)

const McpTokenRoute = McpTokenImport.update({
  id: '/mcp-token',
  path: '/mcp-token',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceRoute = MarketplaceImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRoute,
} as any)

const ExploreRoute = ExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const DebugRoute = DebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const ChangePasswordRoute = ChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicRegisterRoute = PublicRegisterImport.update({
  id: '/public/register',
  path: '/public/register',
  getParentRoute: () => rootRoute,
} as any)

const PublicMarketplaceCallbackRoute = PublicMarketplaceCallbackImport.update({
  id: '/public/marketplace-callback',
  path: '/public/marketplace-callback',
  getParentRoute: () => rootRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  id: '/public/login',
  path: '/public/login',
  getParentRoute: () => rootRoute,
} as any)

const PublicCallbackRoute = PublicCallbackImport.update({
  id: '/public/callback',
  path: '/public/callback',
  getParentRoute: () => rootRoute,
} as any)

const AiCreateRoute = AiCreateImport.update({
  id: '/ai/create',
  path: '/ai/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceImport
      parentRoute: typeof rootRoute
    }
    '/mcp-token': {
      id: '/mcp-token'
      path: '/mcp-token'
      fullPath: '/mcp-token'
      preLoaderRoute: typeof McpTokenImport
      parentRoute: typeof rootRoute
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryImport
      parentRoute: typeof rootRoute
    }
    '/ai/create': {
      id: '/ai/create'
      path: '/ai/create'
      fullPath: '/ai/create'
      preLoaderRoute: typeof AiCreateImport
      parentRoute: typeof rootRoute
    }
    '/public/callback': {
      id: '/public/callback'
      path: '/public/callback'
      fullPath: '/public/callback'
      preLoaderRoute: typeof PublicCallbackImport
      parentRoute: typeof rootRoute
    }
    '/public/login': {
      id: '/public/login'
      path: '/public/login'
      fullPath: '/public/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof rootRoute
    }
    '/public/marketplace-callback': {
      id: '/public/marketplace-callback'
      path: '/public/marketplace-callback'
      fullPath: '/public/marketplace-callback'
      preLoaderRoute: typeof PublicMarketplaceCallbackImport
      parentRoute: typeof rootRoute
    }
    '/public/register': {
      id: '/public/register'
      path: '/public/register'
      fullPath: '/public/register'
      preLoaderRoute: typeof PublicRegisterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp-token': typeof McpTokenRoute
  '/path': typeof PathRoute
  '/query': typeof QueryRoute
  '/ai/create': typeof AiCreateRoute
  '/public/callback': typeof PublicCallbackRoute
  '/public/login': typeof PublicLoginRoute
  '/public/marketplace-callback': typeof PublicMarketplaceCallbackRoute
  '/public/register': typeof PublicRegisterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp-token': typeof McpTokenRoute
  '/path': typeof PathRoute
  '/query': typeof QueryRoute
  '/ai/create': typeof AiCreateRoute
  '/public/callback': typeof PublicCallbackRoute
  '/public/login': typeof PublicLoginRoute
  '/public/marketplace-callback': typeof PublicMarketplaceCallbackRoute
  '/public/register': typeof PublicRegisterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp-token': typeof McpTokenRoute
  '/path': typeof PathRoute
  '/query': typeof QueryRoute
  '/ai/create': typeof AiCreateRoute
  '/public/callback': typeof PublicCallbackRoute
  '/public/login': typeof PublicLoginRoute
  '/public/marketplace-callback': typeof PublicMarketplaceCallbackRoute
  '/public/register': typeof PublicRegisterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/debug'
    | '/explore'
    | '/marketplace'
    | '/mcp-token'
    | '/path'
    | '/query'
    | '/ai/create'
    | '/public/callback'
    | '/public/login'
    | '/public/marketplace-callback'
    | '/public/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-password'
    | '/debug'
    | '/explore'
    | '/marketplace'
    | '/mcp-token'
    | '/path'
    | '/query'
    | '/ai/create'
    | '/public/callback'
    | '/public/login'
    | '/public/marketplace-callback'
    | '/public/register'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/debug'
    | '/explore'
    | '/marketplace'
    | '/mcp-token'
    | '/path'
    | '/query'
    | '/ai/create'
    | '/public/callback'
    | '/public/login'
    | '/public/marketplace-callback'
    | '/public/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DebugRoute: typeof DebugRoute
  ExploreRoute: typeof ExploreRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpTokenRoute: typeof McpTokenRoute
  PathRoute: typeof PathRoute
  QueryRoute: typeof QueryRoute
  AiCreateRoute: typeof AiCreateRoute
  PublicCallbackRoute: typeof PublicCallbackRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMarketplaceCallbackRoute: typeof PublicMarketplaceCallbackRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DebugRoute: DebugRoute,
  ExploreRoute: ExploreRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpTokenRoute: McpTokenRoute,
  PathRoute: PathRoute,
  QueryRoute: QueryRoute,
  AiCreateRoute: AiCreateRoute,
  PublicCallbackRoute: PublicCallbackRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMarketplaceCallbackRoute: PublicMarketplaceCallbackRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/change-password",
        "/debug",
        "/explore",
        "/marketplace",
        "/mcp-token",
        "/path",
        "/query",
        "/ai/create",
        "/public/callback",
        "/public/login",
        "/public/marketplace-callback",
        "/public/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/change-password": {
      "filePath": "change-password.tsx"
    },
    "/debug": {
      "filePath": "debug.tsx"
    },
    "/explore": {
      "filePath": "explore.tsx"
    },
    "/marketplace": {
      "filePath": "marketplace.tsx"
    },
    "/mcp-token": {
      "filePath": "mcp-token.tsx"
    },
    "/path": {
      "filePath": "path.tsx"
    },
    "/query": {
      "filePath": "query.tsx"
    },
    "/ai/create": {
      "filePath": "ai.create.tsx"
    },
    "/public/callback": {
      "filePath": "public/callback.tsx"
    },
    "/public/login": {
      "filePath": "public/login.tsx"
    },
    "/public/marketplace-callback": {
      "filePath": "public/marketplace-callback.tsx"
    },
    "/public/register": {
      "filePath": "public/register.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
